// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewCategory struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type NewMovie struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Year        *int    `json:"year,omitempty"`
	CategoryID  string  `json:"categoryId"`
}
