// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID          *string  `json:"id,omitempty"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Movies      []*Movie `json:"movies"`
}

type Movie struct {
	ID       *string   `json:"id,omitempty"`
	Name     string    `json:"name"`
	Year     int       `json:"year"`
	Category *Category `json:"category"`
}

type NewCategory struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewMovie struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Year        int    `json:"year"`
	CategoryID  string `json:"categoryId"`
}
